### ISSUE TITLE
Unable to Compile

### ISSUE THREAD

**Issue by KarlMarx420** [ElunaLuaEngine/Eluna#275]
When trying to compile https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/24f86437c465449d10f55dee610e1b7c3b3a44bc the compiling failes at [ 84%] Built target scripts.
OS: Debian9
Compiling Log: https://pastebin.com/55mneuYD
https://github.com/TrinityCore/TrinityCore/commit/98fd8d4c748942cc7d7acde97610b7b0688472de is working and https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/1eee7986b6ae was working fine too.

**Comment by Rochet2** [comment]
Cannot reproduce with `-DTOOLS=1 -DWITH_WARNINGS=1 -DWITH_COREDEBUG=1` on travis or on debian 9.

Try running `make` again.
Make sure `LuaEngine.h` file actually exists in your source.

I only managed to get the following, but it seems unrelated and was fixed after retrying make:
```
[ 72%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Northrend/AzjolNerub/Ahnkahet/instance_ahnkahet.cpp.o
In file included from /mnt/c/Users/uname/Documents/Cores/Eluna/core_trinity/trin_wotlk/source/src/server/scripts/Northrend/AzjolNerub/Ahnkahet/boss_herald_volazj.cpp:28:
In file included from /mnt/c/Users/uname/Documents/Cores/Eluna/core_trinity/trin_wotlk/source/src/server/game/AI/ScriptedAI/ScriptedCreature.h:22:
/mnt/c/Users/uname/Documents/Cores/Eluna/core_trinity/trin_wotlk/source/src/server/game/AI/CreatureAI.h:22:10: fatal error: 'UnitAI.h' file not found
#include "UnitAI.h"
         ^
1 error generated.
src/server/scripts/CMakeFiles/scripts.dir/build.make:7862: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/Northrend/AzjolNerub/Ahnkahet/boss_herald_volazj.cpp.o' failed
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/Northrend/AzjolNerub/Ahnkahet/boss_herald_volazj.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1293: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by KarlMarx420** [comment]
LuaEngine.h does not even exist in https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/24f86437c465449d10f55dee610e1b7c3b3a44bc for some reason?

Running make again did not resolve the issue. :/

**Comment by Rochet2** [comment]
LuaEngine folder is a submodule.
You most likely did not follow the installation instructions.

**Comment by KarlMarx420** [comment]
Silly me... I missed step 4.
Thanks for the help!
